### ISSUE TITLE
SimplePos22와 MorphAnalyzer 실행 오류 문의

### ISSUE THREAD

**Issue by shouts77** [haven-jeon/KoNLP#27]
안녕항세요.
KoNLP 공유해 주셔서 우선 감사드립니다.

그런데 KoNLP 패키지에서 SimplePos22와 MorphAnalyzer 실행 시 아래와 같은 에러 메세지가 나옵니다. (SimplePos09로는 정상적으로 결과가 나옴)
Error in .jcall(get("HannanumObj", envir = KoNLP:::.KoNLPEnv), "S", "SimplePos22", : 
java.lang.OutOfMemoryError: Java heap space
Error in .jcall(get("HannanumObj", envir = KoNLP:::.KoNLPEnv), "S", "MorphAnalyzer", : 
java.lang.OutOfMemoryError: Java heap space

무엇때문에 오류가 나는 지 알려주실 수 있는지요?

**Comment by haven-jeon** [comment]
자바 heap 영역의 크기 때문입니다. 동작하는 PC의 메모리를 확인하시고 자바 환경설정에서 메모리를 늘려주세요.
