### ISSUE TITLE
shiny io deploy 시 에러 발생

### ISSUE THREAD

**Issue by jooniis** [haven-jeon/KoNLP#29]
안녕하세요?
만들어주신 패키지 정말 잘 사용하고 있습니다^^

다름이 아니라, 제가 워드 클라우드 생성하는 shiny app 을 만들어,
팀내에서 같이 쓰기 위해 shiny io에 올려보려고 했는데요,
deploy 할때 아래와 같이 에러가 발생하여 rstudio에 쪽에 문의하였더니,
패키지 개발자 분께서 오류를 고쳐주셔야 한다고 회신을 받았습니다.
확인해주심 대단히 감사하겠습니다^^

(오류 메시지는 맨 아래 부분에 있습니다)

building: Building package: KoNLP
################################ Begin Task Log ################################ 
[2016-03-27T00:46:29.686536819+0000] Execute script: packages/build/rJava.sh
+ set -e
+ apt-key adv --keyserver keyserver.ubuntu.com (http://keyserver.ubuntu.com/) --recv-keys 86F44E2A
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.GH0bBoHnbc --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com (http://keyserver.ubuntu.com/) --recv-keys 86F44E2A
gpg: requesting key 86F44E2A from hkp server keyserver.ubuntu.com (http://keyserver.ubuntu.com/)
gpg: key 86F44E2A: public key "Launchpad OpenJDK builds (all archs)" imported
gpg: Total number processed: 1
gpg: imported: 1 (RSA: 1)
+ echo 'deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu precise main'
+ apt-get update -qq
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_precise-updates_universe_source_Sources.gz is not what the server reported 153139 153184
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_precise-security_universe_source_Sources.gz is not what the server reported 53161 53201
+ DEBIAN_FRONTEND=noninteractive
+ apt-get install -y --no-install-recommends openjdk-8-jdk
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
openjdk-8-jre openjdk-8-jre-headless
Suggested packages:
openjdk-8-demo openjdk-8-source visualvm icedtea-8-plugin
openjdk-8-jre-jamvm libnss-mdns fonts-ipafont-gothic fonts-ipafont-mincho
ttf-wqy-microhei ttf-wqy-zenhei ttf-indic-fonts-core ttf-telugu-fonts
ttf-oriya-fonts ttf-kannada-fonts ttf-bengali-fonts
Recommended packages:
libgnome2-0 libgnomevfs2-0 libgconf2-4 ttf-dejavu-extra
The following NEW packages will be installed:
openjdk-8-jdk openjdk-8-jre openjdk-8-jre-headless
0 upgraded, 3 newly installed, 0 to remove and 18 not upgraded.
Need to get 49.7 MB of archives.
After this operation, 138 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/ precise/main openjdk-8-jre-headless amd64 8u72-b15-1~precise1 [37.7 MB]
Get:2 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/ precise/main openjdk-8-jre amd64 8u72-b15-1~precise1 [72.5 kB]
Get:3 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/ precise/main openjdk-8-jdk amd64 8u72-b15-1~precise1 [11.9 MB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 49.7 MB in 5s (9471 kB/s)
Selecting previously unselected package openjdk-8-jre-headless.
(Reading database ... 85150 files and directories currently installed.)
Unpacking openjdk-8-jre-headless (from .../openjdk-8-jre-headless_8u72-b15-1~precise1_amd64.deb) ...
Selecting previously unselected package openjdk-8-jre.
Unpacking openjdk-8-jre (from .../openjdk-8-jre_8u72-b15-1~precise1_amd64.deb) ...
Selecting previously unselected package openjdk-8-jdk.
Unpacking openjdk-8-jdk (from .../openjdk-8-jdk_8u72-b15-1~precise1_amd64.deb) ...
Setting up openjdk-8-jre-headless (8u72-b15-1~precise1) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java to provide /usr/bin/java (java) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/orbd to provide /usr/bin/orbd (orbd) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/servertool to provide /usr/bin/servertool (servertool) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/tnameserv to provide /usr/bin/tnameserv (tnameserv) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode.
Setting up openjdk-8-jre (8u72-b15-1~precise1) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/policytool to provide /usr/bin/policytool (policytool) in auto mode.
Setting up openjdk-8-jdk (8u72-b15-1~precise1) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/appletviewer to provide /usr/bin/appletviewer (appletviewer) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/extcheck to provide /usr/bin/extcheck (extcheck) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/idlj to provide /usr/bin/idlj (idlj) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jar to provide /usr/bin/jar (jar) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jarsigner to provide /usr/bin/jarsigner (jarsigner) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javac to provide /usr/bin/javac (javac) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javadoc to provide /usr/bin/javadoc (javadoc) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javah to provide /usr/bin/javah (javah) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javap to provide /usr/bin/javap (javap) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jcmd to provide /usr/bin/jcmd (jcmd) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jdb to provide /usr/bin/jdb (jdb) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jdeps to provide /usr/bin/jdeps (jdeps) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jhat to provide /usr/bin/jhat (jhat) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jinfo to provide /usr/bin/jinfo (jinfo) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jmap to provide /usr/bin/jmap (jmap) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jps to provide /usr/bin/jps (jps) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jrunscript to provide /usr/bin/jrunscript (jrunscript) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jsadebugd to provide /usr/bin/jsadebugd (jsadebugd) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jstack to provide /usr/bin/jstack (jstack) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jstat to provide /usr/bin/jstat (jstat) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jstatd to provide /usr/bin/jstatd (jstatd) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/native2ascii to provide /usr/bin/native2ascii (native2ascii) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/schemagen to provide /usr/bin/schemagen (schemagen) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/serialver to provide /usr/bin/serialver (serialver) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/wsgen to provide /usr/bin/wsgen (wsgen) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/wsimport to provide /usr/bin/wsimport (wsimport) in auto mode.
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/xjc to provide /usr/bin/xjc (xjc) in auto mode.
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
+ /usr/bin/R CMD javareconf
*** JAVA_HOME is not a valid path, ignoring
Java interpreter : /usr/bin/java
Java version : 1.8.0_72-internal
Java home path : /usr/lib/jvm/java-8-openjdk-amd64/jre
Java compiler : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar

trying to compile and link a JNI program 
detected JNI cpp flags : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/linux
detected JNI linker flags : -L$(JAVA_HOME)/lib/amd64/server -ljvm
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I/usr/lib/jvm/java-8-openjdk-amd64/jre/../include -I/usr/lib/jvm/java-8-openjdk-amd64/jre/../include/linux -fpic -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c conftest.c -o conftest.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o conftest.so conftest.o -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server -ljvm -L/usr/lib/R/lib -lR

JAVA_HOME : /usr/lib/jvm/java-8-openjdk-amd64/jre
Java library path: $(JAVA_HOME)/lib/amd64/server
JNI cpp flags : -I$(JAVA_HOME)/../include -I$(JAVA_HOME)/../include/linux
JNI linker flags : -L$(JAVA_HOME)/lib/amd64/server -ljvm
Updating Java configuration in /usr/lib/R
Done.

[2016-03-27T00:46:51.509207884+0000] Execute script: packages/build/tm.sh
+ set -e
+ apt-get update -qq
+ apt-get install -y antiword poppler-utils
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
antiword poppler-utils
0 upgraded, 2 newly installed, 0 to remove and 18 not upgraded.
Need to get 309 kB of archives.
After this operation, 1094 kB of additional disk space will be used.
Get:1 http://mirrordenver.fdcservers.net/ubuntu/ precise/universe antiword amd64 0.37-8 [170 kB]
Get:2 http://mirrordenver.fdcservers.net/ubuntu/ precise-updates/main poppler-utils amd64 0.18.4-1ubuntu3.1 [139 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 309 kB in 0s (697 kB/s)
Selecting previously unselected package antiword.
(Reading database ... 85502 files and directories currently installed.)
Unpacking antiword (from .../antiword_0.37-8_amd64.deb) ...
Selecting previously unselected package poppler-utils.
Unpacking poppler-utils (from .../poppler-utils_0.18.4-1ubuntu3.1_amd64.deb) ...
Processing triggers for man-db ...
Setting up antiword (0.37-8) ...
Setting up poppler-utils (0.18.4-1ubuntu3.1) ...
[2016-03-27T00:47:29.254237873+0000] Installing R package: xtable (1.8-2)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��xtable�� ...
* DONE (xtable)
[2016-03-27T00:47:29.579550598+0000] Installing R package: magrittr (1.5)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��magrittr�� ...
* DONE (magrittr)
[2016-03-27T00:47:29.848126156+0000] Installing R package: stringi (1.0-1)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��stringi�� ...
* DONE (stringi)
[2016-03-27T00:47:32.357335428+0000] Installing R package: stringr (1.0.0)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��stringr�� ...
* DONE (stringr)
[2016-03-27T00:47:32.619864708+0000] Installing R package: rJava (0.9-8)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��rJava�� ...
* DONE (rJava)
[2016-03-27T00:47:33.060769806+0000] Installing R package: mime (0.4)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��mime�� ...
* DONE (mime)
[2016-03-27T00:47:33.321167335+0000] Installing R package: packrat (0.4.7)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��packrat�� ...
* DONE (packrat)
[2016-03-27T00:47:33.589484244+0000] Installing R package: hash (2.2.6)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��hash�� ...
* DONE (hash)
[2016-03-27T00:47:33.853055729+0000] Installing R package: R6 (2.1.2)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��R6�� ...
* DONE (R6)
[2016-03-27T00:47:34.147142832+0000] Installing R package: RColorBrewer (1.1-2)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��RColorBrewer�� ...
* DONE (RColorBrewer)
[2016-03-27T00:47:34.402586989+0000] Installing R package: NLP (0.1-9)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��NLP�� ...
* DONE (NLP)
[2016-03-27T00:47:34.674752010+0000] Installing R package: digest (0.6.9)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��digest�� ...
* DONE (digest)
[2016-03-27T00:47:34.958295582+0000] Installing R package: memoise (1.0.0)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��memoise�� ...
* DONE (memoise)
[2016-03-27T00:47:35.212587511+0000] Installing R package: htmltools (0.3)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��htmltools�� ...
* DONE (htmltools)
[2016-03-27T00:47:35.476188144+0000] Installing R package: jsonlite (0.9.19)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��jsonlite�� ...
* DONE (jsonlite)
[2016-03-27T00:47:35.889928908+0000] Installing R package: Rcpp (0.12.3)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��Rcpp�� ...
* DONE (Rcpp)
[2016-03-27T00:47:37.177233917+0000] Installing R package: httpuv (1.3.3)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��httpuv�� ...
* DONE (httpuv)
[2016-03-27T00:47:37.576434867+0000] Installing R package: shiny (0.13.1)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��shiny�� ...
* DONE (shiny)
[2016-03-27T00:47:38.330012972+0000] Installing R package: slam (0.1-32)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��slam�� ...
* DONE (slam)
[2016-03-27T00:47:38.592693749+0000] Installing R package: wordcloud (2.5)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��wordcloud�� ...
* DONE (wordcloud)
[2016-03-27T00:47:38.868515066+0000] Installing R package: tm (0.6-2)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��tm�� ...
* DONE (tm)
[2016-03-27T00:47:39.267587598+0000] Installing R package: Sejong (0.01)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��Sejong�� ...
* DONE (Sejong)
[2016-03-27T00:47:39.589284430+0000] Installing R package: tau (0.0-18)
* installing to library ��/usr/local/lib/R/site-library��
* installing *binary* package ��tau�� ...
* DONE (tau)
[2016-03-27T00:47:39.856554530+0000] Building R package: KoNLP (0.76.9)
/mnt/packages/build /mnt
* installing to library ��/usr/local/lib/R/site-library��
* installing *source* package ��KoNLP�� ...
** package ��KoNLP�� successfully unpacked and MD5 sums checked
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error : .onAttach failed in attachNamespace() for 'KoNLP', details:
call: if (all((localeToCharset()[1] == c("UTF-8", "CP949", "EUC-KR")) == 
error: missing value where TRUE/FALSE needed
Error: loading failed
Execution halted
ERROR: loading failed
* removing ��/usr/local/lib/R/site-library/KoNLP��
################################# End Task Log ################################# 
����: Unhandled Exception: Child Task 174749962 failed: Error building image: Error building KoNLP (0.76.9). Build exited with non-zero status: 1
������ �����Ǿ����ϴ�

**Comment by haven-jeon** [comment]
자바 환경 이슈인것으로 보입니다. 아무래도 shiny환경을 자바가 따라가다 보니 발생하는것 같은데, 웹은 웹 서버가 동작하는 서버의 특징(로케일) 등등 많은 설정들이 얽혀서 동작하기 때문에 다분히 KoNLP에 대한 문제로 확정해 이슈를 해결하기가 불가능합니다. 따라서 이 이슈는 팔로업 하지 않기로 하겠습니다. 
감사합니다.
