### ISSUE TITLE
Example of extractNoun() and real result doesn't match

### ISSUE THREAD

**Issue by mikigom** [haven-jeon/KoNLP#33]
In [github wiki](https://github.com/haven-jeon/KoNLP/wiki/KoNLP-examples), the example argues the following:

>extractNoun("롯데마트가 판매하고 있는 흑마늘 양념 치킨이 논란이 되고 있다.")
[1] "롯데마트" "판매"     "흑마늘"   "양념"     "치킨"     "논란"

But on CRAN package, the result differs:

> extractNoun("롯데마트가 판매하고 있는 흑마늘 양념 치킨이 논란이 되고 있다.")
[1] "롯데마트가" "판매"       "흑마늘"     "양념"       "치킨"       "논란"

**Comment by haven-jeon** [comment]
10월 말 업데이트시 이 부분 확인 하도록 하겠습니다. 감사합니다.

**Comment by haven-jeon** [comment]
Sejong 패키지 사전에 해당 단어를 추가해서 해결했습니다. ^^; 

https://github.com/haven-jeon/Sejong/commit/a9667a89f4377462d2404dc99a58709a236edf31
