### ISSUE TITLE
library 호출 시 R Session Aborted 에러

### ISSUE THREAD

**Issue by hjmin88** [haven-jeon/KoNLP#51]
> library(KoNLP) 실행 시

R Session Aborted
R encountered a fatal error. 에러 발생합니다.

> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer     

######################################
R, RStudio, install된 패키지들까지 싹 다 지웠다가 다시 설치해도 똑같네요..

**Comment by haven-jeon** [comment]
에러를 해결하는 사람 입장에서는 해당 에러를 재현해볼 수 있는 방법이 필요합니다.
위의 정보만 가지고 뭐가 문제이고 어떠한 상황이 발생했는지 알 수 없습니다.

**Comment by haven-jeon** [comment]
해당 이슈는 환경 설정의 이슈인 관계로 close 합니다..
