### ISSUE TITLE
패키지 메인테이너 지원

### ISSUE THREAD

**Issue by mrchypark** [haven-jeon/KoNLP#65]
안녕하세요, KoNLP가 CRAN에서 내려가서 설치하는데 어려움이 있습니다.

새롭게 CRAN에 등록하고 이후 이슈에 대해 대응하기 위해 메인테이너로 자원하려고 합니다.

수락해주시면 감사하겠습니다.

**Comment by haven-jeon** [comment]
초대해 드렸습니다.
잘 부탁드립니다.
